### ISSUE TITLE
Build compressor

### ISSUE THREAD

**Issue by anthony-swirldslabs** [hiero-ledger/hiero-cryptography#379]
The compressor build is triggered from a custom Rust build script when Cargo executes.

Our current build system uses Gradle, that uses a special `cargo` task from Hiero build utils. The latter uses `cargo-zigbuild` and `zig` in order to cross-compile Rust code. However, when building the compressor with `zig`, and error occurs:

```
error: symbol _runtime.covctrs not attached to any (sub)section
              note: while parsing /var/folders/gt/n3fxywks2nnbjgmbhhvjh3v40000gp/T/rustcSH7o2S/libsp1_recursion_gnark_ffi-60105640fd0f2cf8.rlib(go.o)
```

This issue seems to be fixed in zig 0.14+ ( https://github.com/ziglang/zig/issues/20243 ), but the `cargo-zigbuild` doesn't fully support zig 0.14+ currently. The idea is to not use `zig` when building the compressor.

However, when native Rust `cargo` is run in the `compressor/` directory, then it errors out because it cannot find stdlib.h when compiling native bindings. This issue has been solved by specifying the include path as:

```
$ CPATH=`llvm-config --includedir`/c++/v1 cargo build --release
```

This command succeeds and produces the compressor binary. Note that specifying the `CPATH` for our current Gradle build doesn't fix the build, so for now we have to go with the native Cargo build, at least for the compressor.

Problems to be solved:
1. "Decouple" the compressor so that the Gradle build doesn't try to build it, yet it should be buildable using the native Cargo.
2. Check the output path. Our Gradle build writes artifacts into `target/<arch>/release/` directory. However, the Cargo build for the compressor puts the binary directly under `target/release/`. This may or may not be an issue for cross-compilation.
3. Add a Gradle task to actually call Cargo for the compressor and check if the full Gradle build produces all the binaries - e.g. the already existing libraps.dylib and the new `compressor` program.
4. Make Gradle copy the compressor into the JAR, same as it does for the `libraps.dylib`.
5. See how to apply the solution to other platforms - they may use something different from the `CPATH`, and also something different from the `llvm-config`.
6. Once every platform works on its own, figure out our cross-compilation build setup so that the compressor is built on all platforms and makes it into the JAR in proper locations.

**Comment by anthony-swirldslabs** [comment]
Interestingly, I didn't make any changes to my configuration, but the

```
`llvm-config --includedir`/c++/v1
```

just stopped working. The build seems to mix MacOS and these llvm headers, and cannot find types used in the llvm headers.

However, using `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include` for `CPATH` solves the problem.

I'm unsure why this happened (probably a newer version of our Rust dependencies got released and automatically picked up - that's the only reasonable explanation.)

But at least we have a workaround.

**Comment by anthony-swirldslabs** [comment]
With the PR above, it looks like on `linux-x86-64`, the compressor was built w/o any issues. I assume that the `CPATH` environment variable is ignored on Linux.

**Comment by anthony-swirldslabs** [comment]
Currently managed to build the compressor for `darwin-aarch64` in GitHub.

The build for `darwin-x86-64` seems to fail with:

```
error: linking with `cc` failed: exit status: 1
  |
  = note: env -u IPHONEOS_DEPLOYMENT_TARGET -u TVOS_DEPLOYMENT_TARGET -u XROS_DEPLOYMENT_TARGET LC_ALL="C" PATH="/Users/runner/.rustup/toolchains/1.85.0-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/bin:/Users/runner/work/hedera-cryptography/hedera-cryptography/build/rust-toolchains/cargo/bin:/Users/runner/work/hedera-cryptography/hedera-cryptography/cryptography/hedera-cryptography-rpm/build/go-sdk/darwin-x86-64/go/bin:/Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.6-7.0.LTS/arm64/Contents/Home/bin:/Users/runner/go/bin:/Users/runner/hostedtoolcache/go/1.24.2/arm64/bin:/opt/homebrew/lib/ruby/gems/3.3.0/bin:/opt/homebrew/opt/ruby@3.3/bin:/Users/runner/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/runner/.cargo/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Library/Frameworks/Python.framework/Versions/Current/bin:/Library/Frameworks/Mono.fr
  = note: some arguments are omitted. use `--verbose` to show all linker arguments
  = note: ld: warning: ignoring duplicate libraries: '-lc++'
          ld: warning: ignoring file '/Users/runner/work/hedera-cryptography/hedera-cryptography/cryptography/hedera-cryptography-rpm/build/target/darwin-x86-64/release/deps/libsp1_recursion_gnark_ffi-02a4a21bc023f210.rlib[24](000013.o)': found architecture 'x86_64', required architecture 'arm64'
...
```

**Comment by anthony-swirldslabs** [comment]
It appears that all the rust libraries were correctly compiled as `x86_64`, but the linker is trying to create a binary for `arm64`. This is likely because this build is running on an arm64 darwin system, and the linker isn't configured to cross-link.

**Comment by anthony-swirldslabs** [comment]
Apparently, `cargo` may need the `--target` argument to cross-compile, so adding it in the latest commit.

**Comment by anthony-swirldslabs** [comment]
Seems like GitHub is now able to build on Mac: https://github.com/hashgraph/hedera-cryptography/actions/runs/16382054965/job/46295377945?pr=381

Need to fix Linux and Windows builds...

**Comment by anthony-swirldslabs** [comment]
Seems like we have a problem trying to cross-compile for linux-aarch64 on a linux x86_64 host. The `CGO_ENABLED=1 go build` command cannot automatically determine the C compiler that should be used to produce code for the target GOOS/GOARCH platform and requires one to define the `CC` environment variable with a name/path to the target compiler.

However, the Go command is invoked from the Rust code, and it so happens that the `rustc` also uses the `CC` environment variable to determine the C compiler for the target platform. And it so happens that we have a Rust dependency, specifically `blake3` which somehow tries to compile native code for multiple platforms. For example, in our case it's trying to compile some x86_64 assembly even though we're building using `cargo --target=aarch64-unknown-linux-gnu`. So the Rust build is trying to use this same compiler defined in the `CC` which actually points to the aarch64 compiler, and obviously it's unable to assemble x86_64 assembly at all.

Ref: https://github.com/hashgraph/hedera-cryptography/actions/runs/16457503001/job/46517902866?pr=381

**Comment by anthony-swirldslabs** [comment]
We cannot define env vars for the go build specifically because it's out of our control: https://github.com/succinctlabs/sp1/blob/dev/crates/recursion/gnark-ffi/build.rs#L22-L33

Similarly, I don't think it's possible to tell the `blake3` not to build native code for platforms other than the target. And again, it's totally outside of our control.

**Comment by anthony-swirldslabs** [comment]
We run into a similar problem when cross-compiling for Windows on a linux x86_64 box: we need to specify CC that points to the cross-compiler, but this interferes with the outer Cargo build for the compressor binary. If CC isn't specified, then the Rust part of the compressor build seems to build fine, but then the `go build` invocation fails.

At this point, we either
* need support from sp1, for which we filed https://github.com/succinctlabs/sp1/issues/2387 , or
* have to abandon cross-compilation and get dedicated GitHub runners on linux-aarch64 and windows to build for these platforms.

**Comment by anthony-swirldslabs** [comment]
I've been trying to use `clang` for linux-aarch64 builds, and with the help of `CCC_OVERRIDE_OPTIONS` it seems to went almost through. However, the latest error is:
```
/usr/bin/aarch64-linux-gnu-ar: no such file or directory
```
when trying to link the Go binary. I've made sure I installed the `binutils-aarch64-linux-gnu` package, and the build log indicate it is installed. The list of files for this package claims that `/usr/bin/aarch64-linux-gnu-ar` is supposed to be present: https://packages.debian.org/sid/amd64/binutils-aarch64-linux-gnu/filelist

Yet, we're getting this error... Not sure how to proceed further.

**Comment by anthony-swirldslabs** [comment]
Instead of using `clang`, I forked `sp1` and applied https://github.com/anthony-swirldslabs/sp1/commit/1e7960a8499e50f6aeacd3cadb2355c8cadd4252 .

Using the fork with `SP1_FFI_ENV_FOR_GO` and specifying `CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER` resolved the linux-aarch64 build issue:

https://github.com/hashgraph/hedera-cryptography/actions/runs/16580167652/job/46894170514?pr=381


On to building for windows-x86...

**Comment by anthony-swirldslabs** [comment]
I'm trying to use `clang` with `cgo` for Windows build because we use it for our outer Cargo build currently (because we use it for building the TSS lib for Windows arch currently.)

However, I've just discovered

https://github.com/golang/go/issues/17014

which is still open. It appears that Go doesn't support `clang`, at least not on Windows. But we use `clang-cl` which emulates Windows behavior. So this isn't going to work.

I'll give a quick try with clang19 to see if that changes anything.

**Comment by anthony-swirldslabs** [comment]
Since the last comment, I switched from `clang` to `mingw`, and it's been going with variable success. I managed to get it to build for `linux-aarch64`. So at this point `windows-x86_64` is the only platform that we cannot build for.

While I'm still unable to build for Windows on Linux in GitHub, I seem to have managed to build for Windows on my Mac using the following command:

```
$ SP1_GNARK_FFI_SKIP_MAC_FRAMEWORKS=true BINDGEN_EXTRA_CLANG_ARGS="-I/opt/homebrew/Cellar/mingw-w64/13.0.0/toolchain-x86_64/x86_64-w64-mingw32/include" CARGO_BUILD_TARGET=x86_64-pc-windows-gnu GOOS=windows GOARCH=amd64 GOFLAGS="-v -x" SP1_GNARK_FFI_GO_ENVS="CC=x86_64-w64-mingw32-gcc;CPATH=/opt/homebrew/Cellar/mingw-w64/13.0.0/toolchain-x86_64/x86_64-w64-mingw32/include" CC_x86_64_pc_windows_gnu=x86_64-w64-mingw32-gcc CFLAGS_x86_64_pc_windows_gnu="-I/opt/homebrew/Cellar/mingw-w64/13.0.0/toolchain-x86_64/x86_64-w64-mingw32/include" ../../../../../../build/rust-toolchains/cargo/bin/cargo build --release  --target=x86_64-pc-windows-gnu --target-dir ../../../../build/target/win32-x86-64-msvc
```

and it actually produced a `compressor.exe` in the build directory.

So if building on linux doesn't go further, we may try and cross-build for windows on mac.

**Comment by anthony-swirldslabs** [comment]
Wow, the build for windows on linux just succeeded: https://github.com/hashgraph/hedera-cryptography/actions/runs/16736675140/job/47376800402?pr=381

**Comment by anthony-swirldslabs** [comment]
I submitted a PR for `sp1` at https://github.com/succinctlabs/sp1/pull/2418

However, it's targeting the `dev` branch which is at `sp1 version 5.2.1` currently. After I merged all the latest commits from `dev` to make the PR branch up to date, the TSS lib build broke. It requires an upgrade of Rust to 1.86, but even then it fails to build some Rust libraries that use native code (I tested it on my Mac.)

So I've created a new fork branch at https://github.com/anthony-swirldslabs/sp1/tree/go-build-config-5.1.0 which is based on `sp1 version 5.1.0`. I'm currently trying to see if a local build succeed.

So until/unless we resolve the issues related to the upgrade of `sp1`, which is outside of scope of this story, we won't be able to benefit from merging our patch into sp1.
